import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {rooms,type Artwork,type Room} from './data';
import {tourPose} from './tour';
export type Hit={work:Artwork;x:number;y:number;label:boolean}|null;
type Callbacks={onReady:()=>void;onSelect:(a:Artwork)=>void;onHover:(h:Hit)=>void;onRoom:(r:Room)=>void;onError:()=>void};
type Mount={work:Artwork;group:THREE.Group;surface:THREE.Mesh;room:Room;position:THREE.Vector3;side:number;loaded:boolean;requestId:number};
export class GalleryEngine{
 scene=new THREE.Scene();camera:THREE.PerspectiveCamera;renderer:THREE.WebGLRenderer;mounts:Mount[]=[];groups:THREE.Group[]=[];keys=new Set<string>();activeRoom=rooms[0];blocked=false;disposed=false;animation=0;frameTime=0;yaw=.30;pitch=-.035;moving=false;drag=false;down={x:0,y:0};pointer=new THREE.Vector2(2,2);raycaster=new THREE.Raycaster();targets:THREE.Object3D[]=[];occluders:THREE.Object3D[]=[];tourClock:(()=>number|null)|null=null;textures=new THREE.TextureLoader();lastTick=performance.now();tour=false;tourTime=0;tourDuration=65;customMount:Mount|null=null;lightIntensity=1.5;studioLight:THREE.SpotLight|null=null;onTourProgress:((n:number)=>void)|null=null;onTourEnd:(()=>void)|null=null;resizeObserver:ResizeObserver;callbacks:Callbacks;host:HTMLElement;spotlights:THREE.SpotLight[]=[];sun:THREE.DirectionalLight|null=null;pendingAssets=0;lastRoomCheck=0;lastHover='';transition:{from:THREE.Vector3;to:THREE.Vector3;start:number;fromYaw:number;toYaw:number;fromPitch:number;toPitch:number}|null=null;
 constructor(host:HTMLElement,callbacks:Callbacks){
 this.host=host;this.callbacks=callbacks;this.camera=new THREE.PerspectiveCamera(57,host.clientWidth/host.clientHeight,.08,250);this.camera.position.set(-1,2.35,6.8);this.camera.rotation.order='YXZ';
 this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.setSize(host.clientWidth,host.clientHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;host.appendChild(this.renderer.domElement);this.scene.background=new THREE.Color('#c3cbc9');this.scene.fog=new THREE.Fog('#c3cbc9',38,145);
 const pmrem=new THREE.PMREMGenerator(this.renderer);const env=new RoomEnvironment();this.scene.environment=pmrem.fromScene(env,.03).texture;env.dispose();pmrem.dispose();
 this.scene.add(new THREE.HemisphereLight('#e8f0ff','#897761',2.15));const sun=new THREE.DirectionalLight('#fff3dc',2.6);sun.position.set(6,20,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-26;sun.shadow.camera.right=26;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-35;sun.shadow.normalBias=.04;sun.shadow.bias=-.0003;this.scene.add(sun);this.scene.add(sun.target);sun.target.position.set(0,0,-12);this.sun=sun;
 for(let i=0;i<8;i++){const light=new THREE.SpotLight('#ffe2ae',38,12,.52,.8,2);light.castShadow=i<2;light.shadow.mapSize.set(512,512);light.shadow.bias=-.0002;light.shadow.normalBias=.015;this.scene.add(light,light.target);this.spotlights.push(light)}
 const stone=new THREE.MeshStandardMaterial({color:'#bebcb2',roughness:.6,metalness:.05});const bronze=new THREE.MeshStandardMaterial({color:'#665344',metalness:.85,roughness:.3});const ceiling=new THREE.MeshStandardMaterial({color:'#454c46',roughness:.95});
 const floor=this.box([rooms.length*22+4,.22,12],[rooms.at(-1)!.x/2,-.11,14],stone);this.scene.add(floor);
 rooms.forEach(room=>this.buildRoom(room,stone,bronze,ceiling));
 const front=this.box([rooms.length*22+4,6.5,.25],[rooms.at(-1)!.x/2,3.25,20],new THREE.MeshStandardMaterial({color:'#b9c2b3',roughness:.85}));this.scene.add(front);
 const sign=this.text('ASTRA GALLERY    ✦    CODEX BILLBOARDS',1600,150,'#384338','#dedfcd',55);sign.position.set(rooms.at(-1)!.x/2,3.3,19.8);sign.rotation.y=Math.PI;sign.scale.set(20,1.85,1);this.scene.add(sign);
 this.resizeObserver=new ResizeObserver(()=>{if(this.disposed)return;this.camera.aspect=host.clientWidth/host.clientHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(host.clientWidth,host.clientHeight)});this.resizeObserver.observe(host);this.occluders=[front,...this.groups.flatMap(g=>g.children.filter(o=>o instanceof THREE.Mesh))];this.bindEvents();this.loadArchitecture();this.updateVisibility();this.tick();setTimeout(()=>{if(!this.disposed)callbacks.onReady()},450);
 }
 box(size:number[],pos:number[],mat:THREE.Material,bevel=0){const g=bevel?new RoundedBoxGeometry(size[0],size[1],size[2],2,bevel):new THREE.BoxGeometry(size[0],size[1],size[2]);const m=new THREE.Mesh(g,mat);m.position.set(pos[0],pos[1],pos[2]);m.receiveShadow=true;m.castShadow=true;return m}
 text(content:string,w:number,h:number,color:string,bg:string,fontSize:number){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${fontSize}px Georgia`;ctx.fillText(content,w/2,h/2,w-45);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({map:t,toneMapped:false}))}
 buildRoom(room:Room,stone:THREE.MeshStandardMaterial,bronze:THREE.MeshStandardMaterial,ceiling:THREE.MeshStandardMaterial){const group=new THREE.Group();group.position.x=room.x;this.scene.add(group);this.groups.push(group);const center=8-room.length/2;const wall=new THREE.MeshStandardMaterial({color:room.color,roughness:.91});group.add(this.box([18,.2,room.length],[0,-.1,center],stone));for(const side of [-1,1]){group.add(this.box([.3,6.7,room.length],[side*9,3.35,center],wall));group.add(this.box([.36,.13,room.length],[side*8.97,.1,center],bronze));group.add(this.box([.36,.065,room.length],[side*8.8,5.8,center],bronze));group.add(this.box([6.7,6.7,.35],[side*5.65,3.35,8],wall));group.add(this.box([.14,4.8,.45],[side*2.2,2.4,8],bronze));}group.add(this.box([4.4,1.9,.35],[0,5.75,8],wall));group.add(this.box([18,6.7,.3],[0,3.35,8-room.length],wall));
 for(const side of [-1,1])group.add(this.box([5.8,.2,room.length],[side*6.1,6.6,center],ceiling));const sky=new THREE.MeshStandardMaterial({color:'#e4edeb',emissive:'#e0eced',emissiveIntensity:.75,roughness:.25});const skylight=this.box([6.4,.1,room.length],[0,6.7,center],sky);skylight.castShadow=false;group.add(skylight);for(let z=6;z>8-room.length;z-=3){group.add(this.box([18,.16,.12],[0,6.43,z],bronze));}
 const title=this.text(room.name,1536,220,'#4c5145',room.color,93);title.position.set(0,3.9,8-room.length+.18);title.scale.set(12,1.72,1);group.add(title);const sub=this.text('ASTRA  /  '+room.number+'  /  CODEX BILLBOARDS',1024,120,'#727566',room.color,35);sub.position.set(0,2.7,8-room.length+.19);sub.scale.set(8,.94,1);group.add(sub);
 const doorway=this.text(room.number+'   '+room.name.toUpperCase(),1024,120,'#e2cba2','#454c46',48);doorway.position.set(0,5.6,8.21);doorway.scale.set(5,.59,1);group.add(doorway);
 for(let z=-20;z>8-room.length+8;z-=24){for(const side of [-1,1]){group.add(this.box([6.35,6.5,.3],[side*5.8,3.25,z],wall));group.add(this.box([.1,4.9,.4],[side*2.6,2.45,z],bronze));}group.add(this.box([5.3,1.6,.3],[0,5.7,z],wall));}
 room.works.forEach((work,i)=>this.addArtwork(work,room,group,i));
 for(let z=-9;z>8-room.length+7;z-=24){const bench=this.box([3.5,.17,.78],[0,.5,z],new THREE.MeshStandardMaterial({color:'#4f3529',roughness:.42}),.09);bench.name='fallbackBench';group.add(bench);for(const x of [-1.25,1.25]){const leg=this.box([.09,.5,.5],[x,.25,z],bronze);leg.name='fallbackBench';group.add(leg);}}
 }
 addArtwork(work:Artwork,room:Room,parent:THREE.Object3D,index:number){const side=index%2===0?-1:1;const z=1-Math.floor(index/2)*6;const group=new THREE.Group();group.position.set(side*8.72,2.8,z);group.rotation.y=side===-1?Math.PI/2:-Math.PI/2;parent.add(group);let width=4.6,height=width*work.height/work.width;if(height>3.15){height=3.15;width=height*work.width/work.height;}
 const frameMat=new THREE.MeshStandardMaterial({color:room.id==='fame'?'#827057':'#393d35',metalness:.72,roughness:.3});group.add(this.box([width+.20,height+.20,.13],[0,0,-.065],frameMat,.025));const mat=new THREE.MeshStandardMaterial({color:'#ffffff',roughness:.75,metalness:0});const surface=new THREE.Mesh(new THREE.PlaneGeometry(width,height),mat);surface.position.z=.014;surface.userData={work,label:false};group.add(surface);this.targets.push(surface);
 const note=this.text((work.handle?'@'+work.handle:'Anonymous creator')+'  ·  '+work.votes.toLocaleString()+' votes',512,80,'#454c3e','#eeeadb',21);note.scale.set(2.15,.314,1);note.position.set((width-2.15)/2,-height/2-.35,.015);note.userData={work,label:true};group.add(note);this.targets.push(note);
 if(room.id==='fame'){const rank=this.text(String(work.rank).padStart(2,'0'),128,128,'#6b5c43',room.color,66);rank.scale.set(.4,.4,1);rank.position.set(-width/2-.53,height/2-.1,-.002);group.add(rank)}
 const lamp=new THREE.Mesh(new THREE.CylinderGeometry(.105,.135,.37,16),frameMat);lamp.position.set(0,2.78,.65);lamp.rotation.x=.48;group.add(lamp);const emitter=new THREE.Mesh(new THREE.CircleGeometry(.115,16),new THREE.MeshBasicMaterial({color:'#fff1ca'}));emitter.position.set(0,2.59,.73);emitter.rotation.x=-1.09;group.add(emitter);
 const glowCanvas=document.createElement('canvas');glowCanvas.width=128;glowCanvas.height=128;const ctx=glowCanvas.getContext('2d')!;const grad=ctx.createRadialGradient(64,38,2,64,64,64);grad.addColorStop(0,'rgba(255,232,184,.36)');grad.addColorStop(.6,'rgba(255,232,184,.14)');grad.addColorStop(1,'rgba(255,232,184,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);const glow=new THREE.Mesh(new THREE.PlaneGeometry(6,5.5),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(glowCanvas),transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,opacity:.38}));glow.position.set(0,.35,-.12);group.add(glow);
 const mount={work,group,surface,room,position:new THREE.Vector3(room.x+side*8.7,2.8,z),side,loaded:false,requestId:0};this.mounts.push(mount);return mount;
 }
 updateVisibility(){this.groups.forEach((g,i)=>g.visible=Math.abs(this.camera.position.x-rooms[i].x)<34);const near=this.mounts.filter(m=>Math.abs(this.camera.position.x-m.room.x)<12).sort((a,b)=>this.camera.position.distanceToSquared(a.position)-this.camera.position.distanceToSquared(b.position)).slice(0,8);this.spotlights.forEach((light,i)=>{const m=near[i];light.visible=!!m;if(m){light.position.set(m.position.x-m.side*1,5.65,m.position.z);light.target.position.copy(m.position);light.intensity=m.room.id==='studio'?38*this.lightIntensity:42;}});if(this.sun){this.sun.position.x=this.activeRoom.x+6;this.sun.target.position.x=this.activeRoom.x;}for(const m of this.mounts){if(m.work.id!=='your-billboard'&&m.loaded&&(Math.abs(this.camera.position.x-m.room.x)>45||Math.abs(this.camera.position.z-m.position.z)>70)){const mat=m.surface.material as THREE.MeshStandardMaterial;mat.map?.dispose();mat.map=null;mat.emissiveMap=null;mat.emissiveIntensity=0;mat.needsUpdate=true;m.loaded=false;m.requestId++;}if(m.loaded||Math.abs(this.camera.position.x-m.room.x)>28||Math.abs(this.camera.position.z-m.position.z)>34)continue;m.loaded=true;const requestId=++m.requestId;this.textures.load(m.work.image,t=>{if(this.disposed||requestId!==m.requestId){t.dispose();return}t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());const mat=m.surface.material as THREE.MeshStandardMaterial;mat.map=t;mat.emissiveMap=t;mat.emissive.set('#ffffff');mat.emissiveIntensity=.16;mat.needsUpdate=true},undefined,()=>{if(requestId===m.requestId)m.loaded=false})}}
 navigate(id:string){const room=rooms.find(r=>r.id===id);if(!room)return;this.tour=false;this.camera.position.set(room.x-1,2.35,6.8);this.yaw=.3;this.pitch=-.035;this.transition=null;this.setRoom(room);this.updateVisibility()}
 setRoom(room:Room){if(room.id!==this.activeRoom.id){this.activeRoom=room;this.callbacks.onRoom(room)}}
 focus(work:Artwork){const m=this.mounts.find(m=>m.work.id===work.id);if(!m)return;this.tour=false;this.setRoom(m.room);const to=new THREE.Vector3(m.room.x+m.side*3.7,2.65,m.position.z+1);this.transition={from:this.camera.position.clone(),to,start:performance.now(),fromYaw:this.yaw,toYaw:m.side===-1?Math.PI/2:-Math.PI/2,fromPitch:this.pitch,toPitch:.025};if(this.camera.position.distanceTo(to)>24){this.camera.position.copy(to);this.yaw=this.transition.toYaw;this.pitch=.025;this.transition=null}this.updateVisibility()}
 canWalk(x:number,z:number){if(z>=8.65&&z<19.25&&x>-9&&x<rooms.at(-1)!.x+9)return true;return rooms.some(r=>{if(!(Math.abs(x-r.x)<8.15&&z<8.7&&z>8-r.length+.8&&(z<7.4||Math.abs(x-r.x)<1.7)))return false;for(let divider=-20;divider>8-r.length+8;divider-=24){if(Math.abs(z-divider)<.65&&Math.abs(x-r.x)>2)return false;}for(let bench=-9;bench>8-r.length+7;bench-=24){if(Math.abs(z-bench)<.75&&Math.abs(x-r.x)<2.3)return false;}if(Math.abs(z-(8-r.length+5))<1&&Math.abs(x-r.x)<1)return false;return true;})}
 move(dx:number,dz:number){const p=this.camera.position;const x=p.x+dx,z=p.z+dz;if(this.canWalk(x,p.z))p.x=x;if(this.canWalk(p.x,z))p.z=z}
 bindEvents(){const c=this.renderer.domElement;c.addEventListener('pointerdown',this.pointerDown);c.addEventListener('pointermove',this.pointerMove);c.addEventListener('pointerup',this.pointerUp);c.addEventListener('pointercancel',this.pointerCancel);c.addEventListener('pointerleave',this.pointerLeave);window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);window.addEventListener('blur',this.blur);c.addEventListener('webglcontextlost',this.contextLost)}
 contextLost=(e:Event)=>{e.preventDefault();this.callbacks.onError()};
 keyDown=(e:KeyboardEvent)=>{if(this.blocked||/INPUT|TEXTAREA/.test((e.target as HTMLElement)?.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift'].includes(k)){e.preventDefault();if(this.tour){this.stopTour();this.onTourEnd?.()}this.keys.add(k)};if(k==='escape')this.keys.clear()};keyUp=(e:KeyboardEvent)=>this.keys.delete(e.key.toLowerCase());blur=()=>{this.keys.clear();this.drag=false};
 pointerDown=(e:PointerEvent)=>{if(this.blocked)return;const rect=this.host.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.drag=true;this.moving=false;this.down={x:e.clientX,y:e.clientY};this.renderer.domElement.setPointerCapture(e.pointerId)};
 pointerMove=(e:PointerEvent)=>{const rect=this.host.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);if(this.drag&&!this.blocked){const dx=e.clientX-this.down.x,dy=e.clientY-this.down.y;if(Math.abs(dx)+Math.abs(dy)>2){this.moving=true;if(this.tour){this.stopTour();this.onTourEnd?.()}this.transition=null;this.yaw-=dx*.003;this.pitch=THREE.MathUtils.clamp(this.pitch-dy*.003,-.72,.72);this.down={x:e.clientX,y:e.clientY};this.callbacks.onHover(null)}}else if(!this.blocked)this.hover(e.clientX,e.clientY)};
 pointerUp=(e:PointerEvent)=>{if(this.drag&&!this.moving&&!this.blocked){this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.pickArtwork();if(hit)this.callbacks.onSelect(hit.object.userData.work)}this.drag=false;this.renderer.domElement.releasePointerCapture(e.pointerId)};
 pointerCancel=()=>{this.drag=false};pointerLeave=()=>{if(!this.drag){this.lastHover='';this.callbacks.onHover(null)}};
 hover(x:number,y:number){this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.pickArtwork();this.renderer.domElement.style.cursor=hit?'pointer':'grab';const id=hit?.object.userData.work.id||'';if(this.lastHover!==id){this.lastHover=id;this.callbacks.onHover(hit?{work:hit.object.userData.work,x,y,label:hit.object.userData.label}:null)}}
 tick=()=>{if(this.disposed)return;this.animation=requestAnimationFrame(this.tick);const now=performance.now();const dt=Math.min((now-this.lastTick)/1000,.05);this.lastTick=now;if(!this.blocked){if(this.transition){const tr=this.transition;const f=Math.min(1,(performance.now()-tr.start)/900);const s=f*f*(3-2*f);this.camera.position.lerpVectors(tr.from,tr.to,s);this.yaw=THREE.MathUtils.lerp(tr.fromYaw,tr.toYaw,s);this.pitch=THREE.MathUtils.lerp(tr.fromPitch,tr.toPitch,s);if(f===1)this.transition=null}else{const speed=(this.keys.has('shift')?8:4.6)*dt;let forward=Number(this.keys.has('w')||this.keys.has('arrowup'))-Number(this.keys.has('s')||this.keys.has('arrowdown'));let right=Number(this.keys.has('d'))-Number(this.keys.has('a'));if(this.keys.has('arrowleft'))this.yaw+=dt*1.2;if(this.keys.has('arrowright'))this.yaw-=dt*1.2;if(forward||right){const norm=Math.hypot(forward,right);forward/=norm;right/=norm;this.move((-Math.sin(this.yaw)*forward+Math.cos(this.yaw)*right)*speed,(-Math.cos(this.yaw)*forward-Math.sin(this.yaw)*right)*speed)}}}
 if(this.tour&&!this.blocked){const mediaTime=this.tourClock?.();this.tourTime=mediaTime==null?this.tourTime+dt:mediaTime;this.setTourTime(this.tourTime);if(this.tourTime>=65){this.tour=false;this.onTourEnd?.()}}else this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');this.lastRoomCheck+=dt;if(this.lastRoomCheck>.4){this.lastRoomCheck=0;this.updateVisibility();const r=rooms.find(r=>Math.abs(this.camera.position.x-r.x)<9&&this.camera.position.z<8.5);if(r)this.setRoom(r)}this.renderer.render(this.scene,this.camera)};

 loadArchitecture(){
 const gltf=new GLTFLoader();this.pendingAssets+=2;
 gltf.load('/models/bench.glb',asset=>{this.pendingAssets--;if(this.disposed)return;this.groups.forEach((group,ri)=>{const old=group.children.filter(o=>o.name==='fallbackBench');old.forEach(o=>{group.remove(o);const m=o as THREE.Mesh;m.geometry.dispose()});for(let z=-9;z>8-rooms[ri].length+7;z-=24){const bench=asset.scene.clone(true);bench.position.set(0,0,z);bench.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});group.add(bench)}})},undefined,()=>this.pendingAssets--);
 gltf.load('/models/sculpture.glb',asset=>{this.pendingAssets--;if(this.disposed)return;this.groups.forEach((group,i)=>{const sculpture=asset.scene.clone(true);sculpture.position.set(0,-.008,8-rooms[i].length+5);sculpture.rotation.y=.5;sculpture.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});group.add(sculpture)})},undefined,()=>this.pendingAssets--);
 this.groups.forEach((group,i)=>{const mat=new THREE.MeshPhysicalMaterial({color:'#efeee9',roughness:.46,metalness:.04,clearcoat:.22,clearcoatRoughness:.35});for(const [file,key] of [['basecolor','map'],['normal','normalMap'],['roughness','roughnessMap']] as const){this.textures.load('/textures/limestone_'+file+'.png',t=>{if(this.disposed){t.dispose();return}t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(9,rooms[i].length/2);if(key==='map')t.colorSpace=THREE.SRGBColorSpace;mat[key]=t;mat.needsUpdate=true})}mat.normalScale.set(.24,.24);const floor=group.children[0] as THREE.Mesh;floor.material=mat;
 // Fine expansion joints and bronze trim give the stone floor a human scale.
 const seam=new THREE.MeshStandardMaterial({color:'#827f73',transparent:true,opacity:.17,roughness:1});for(let z=6;z>8-rooms[i].length;z-=3)group.add(this.box([17.8,.004,.014],[0,.008,z],seam));for(const x of [-6,-3,0,3,6])group.add(this.box([.012,.004,rooms[i].length],[x,.008,8-rooms[i].length/2],seam));
 });
 const studio=rooms.at(-1)!;const g=this.groups.at(-1)!;const w:Artwork={id:'your-billboard',handle:null,votes:0,imageUrl:'',pageUrl:'',width:1600,height:900,room:'studio',rank:0,image:'',thumb:'',title:'Your billboard'};this.customMount=this.addArtwork(w,studio,g,0);this.customMount.loaded=true;const label=this.text('YOUR NEXT BIG IDEA',1280,720,'#d4bd95','#293b30',86);(this.customMount.surface.material as THREE.MeshStandardMaterial).map=(label.material as THREE.MeshBasicMaterial).map;(this.customMount.surface.material as THREE.MeshStandardMaterial).needsUpdate=true;
 }
 setCustomImage(url:string,width:number,height:number){if(!this.customMount)return;const m=this.customMount;m.requestId++;const parent=m.group.parent!;this.targets=this.targets.filter(o=>o.parent!==m.group);parent.remove(m.group);this.mounts=this.mounts.filter(a=>a!==m);m.group.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const material of Array.isArray(o.material)?o.material:[o.material]){Object.values(material).forEach(v=>{if(v instanceof THREE.Texture)v.dispose()});material.dispose()}}});const work={...m.work,image:url,imageUrl:url,width,height};this.customMount=this.addArtwork(work,m.room,parent,0);this.updateVisibility();this.focus(work);}
 setLighting(value:number){this.lightIntensity=value;this.updateVisibility()}
 startTour(){this.keys.clear();this.transition=null;this.tourTime=0;this.tour=true;this.setTourTime(0)}
 stopTour(){this.tour=false;this.yaw=this.camera.rotation.y;this.pitch=this.camera.rotation.x;this.recoverWalkPosition()}
 isVisible(o:THREE.Object3D){let current:THREE.Object3D|null=o;while(current){if(!current.visible)return false;current=current.parent}return true}
 pickArtwork(){const hit=this.raycaster.intersectObjects([...this.targets,...this.occluders].filter(o=>this.isVisible(o)),false)[0];return hit&&hit.distance<25&&hit.object.userData.work&&(hit.object.userData.work.id!=='your-billboard'||hit.object.userData.work.image)?hit:undefined}
 recoverWalkPosition(){const p=this.camera.position;if(this.canWalk(p.x,p.z))return;for(let radius=.3;radius<8;radius+=.3){for(let n=0;n<16;n++){const angle=n*Math.PI/8,x=p.x+Math.cos(angle)*radius,z=p.z+Math.sin(angle)*radius;if(this.canWalk(x,z)){p.x=x;p.z=z;return}}}this.navigate(this.activeRoom.id)}
 setTourTime(seconds:number){const pose=tourPose(seconds);this.camera.position.set(...pose.position);this.camera.lookAt(new THREE.Vector3(...pose.target));this.yaw=this.camera.rotation.y;this.pitch=this.camera.rotation.x;this.setRoom(rooms[pose.roomIndex]);this.onTourProgress?.(seconds/65)}
 capture(){return this.renderer.domElement.toDataURL('image/png')}

 dispose(){this.disposed=true;cancelAnimationFrame(this.animation);this.resizeObserver.disconnect();window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('blur',this.blur);this.scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){for(const mat of Array.isArray(m.material)?m.material:[m.material]){Object.values(mat).forEach(v=>{if(v instanceof THREE.Texture)v.dispose()});mat.dispose()}}});this.scene.environment?.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}
